name = "starlink-geoip-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
STARLINK_FEED_URL = "https://geoip.starlinkisp.net/feed.csv"
IPV4_LIST_NAME = "Starlink GeoIP - IPv4"
IPV6_LIST_NAME = "Starlink GeoIP - IPv6"

[triggers]
crons = ["0 18 * * *"] # Daily at 18:00 UTC (= KST 03:00)
